// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0cbE3JaIT195a4jJZ015uDlBpGswHjl4',
    appId: '1:384693195486:web:365ada228e1cecd682e84f',
    messagingSenderId: '384693195486',
    projectId: 'movie-ticket-8a583',
    authDomain: 'movie-ticket-8a583.firebaseapp.com',
    databaseURL: 'https://movie-ticket-8a583-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movie-ticket-8a583.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDII5xugP5MLCW-OLphr0cuCFuU7Akbzvc',
    appId: '1:384693195486:android:5ed1ceed1309af1f82e84f',
    messagingSenderId: '384693195486',
    projectId: 'movie-ticket-8a583',
    databaseURL: 'https://movie-ticket-8a583-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movie-ticket-8a583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSImEVatD0vQSRtTM48aWTiHTnZQyXBv4',
    appId: '1:384693195486:ios:3f420796ef24b8d682e84f',
    messagingSenderId: '384693195486',
    projectId: 'movie-ticket-8a583',
    databaseURL: 'https://movie-ticket-8a583-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movie-ticket-8a583.firebasestorage.app',
    iosClientId: '384693195486-a35r1f0ilo5kfij0da2eet5924ghj06i.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTicket',
  );
}
